
var S;S||(S=typeof Module !== 'undefined' ? Module : {});
(function(){function ja(c){return a.locateFile?a.locateFile(c,v):v+c}function T(c){var b=a["_"+c];b||w("Assertion failed: Cannot call unknown function "+(c+", make sure it is exported"));return b}function U(c,b,d,e){var f={string:function(h){var l=0;if(null!==h&&void 0!==h&&0!==h){var k=(h.length<<2)+1;l=J(k);var n=H,g=l;if(0<k){k=g+k-1;for(var r=0;r<h.length;++r){var t=h.charCodeAt(r);if(55296<=t&&57343>=t){var K=h.charCodeAt(++r);t=65536+((t&1023)<<10)|K&1023}if(127>=t){if(g>=k)break;n[g++]=t}else{if(2047>=
t){if(g+1>=k)break;n[g++]=192|t>>6}else{if(65535>=t){if(g+2>=k)break;n[g++]=224|t>>12}else{if(g+3>=k)break;n[g++]=240|t>>18;n[g++]=128|t>>12&63}n[g++]=128|t>>6&63}n[g++]=128|t&63}}n[g]=0}}return l},array:function(h){var l=J(h.length);V.set(h,l);return l}};c=T(c);var p=[],m=0;if(e)for(var q=0;q<e.length;q++){var y=f[d[q]];y?(0===m&&(m=W()),p[q]=y(e[q])):p[q]=e[q]}d=c.apply(null,p);return d=function(h){0!==m&&X(m);if("string"===b)if(h){var l=H;for(var k=h+NaN,n=h;l[n]&&!(n>=k);)++n;if(16<n-h&&l.subarray&&
Y)l=Y.decode(l.subarray(h,n));else{for(k="";h<n;){var g=l[h++];if(g&128){var r=l[h++]&63;if(192==(g&224))k+=String.fromCharCode((g&31)<<6|r);else{var t=l[h++]&63;g=224==(g&240)?(g&15)<<12|r<<6|t:(g&7)<<18|r<<12|t<<6|l[h++]&63;65536>g?k+=String.fromCharCode(g):(g-=65536,k+=String.fromCharCode(55296|g>>10,56320|g&1023))}}else k+=String.fromCharCode(g)}l=k}}else l="";else l="boolean"===b?!!h:h;return l}(d)}function w(c){if(a.onAbort)a.onAbort(c);C(c);Z=!0;throw new WebAssembly.RuntimeError("abort("+
c+"). Build with -s ASSERTIONS=1 for more info.");}function aa(c){return c.startsWith("data:application/octet-stream;base64,")}function ba(c){try{if(c==u&&D)return new Uint8Array(D);if(L)return L(c);throw"both async and sync fetching of the wasm failed";}catch(b){w(b)}}function ka(){if(!D&&(ca||E)){if("function"===typeof fetch&&!u.startsWith("file://"))return fetch(u,{credentials:"same-origin"}).then(function(c){if(!c.ok)throw"failed to load wasm binary file at '"+u+"'";return c.arrayBuffer()}).catch(function(){return ba(u)});
if(M)return new Promise(function(c,b){M(u,function(d){c(new Uint8Array(d))},b)})}return Promise.resolve().then(function(){return ba(u)})}function N(c){for(;0<c.length;){var b=c.shift();if("function"==typeof b)b(a);else{var d=b.M;"number"===typeof d?void 0===b.s?O.get(d)():O.get(d)(b.s):d(void 0===b.s?null:b.s)}}}function P(){function c(){if(!I&&(I=!0,a.calledRun=!0,!Z)){N(da);if(a.onRuntimeInitialized)a.onRuntimeInitialized();if(a.postRun)for("function"==typeof a.postRun&&(a.postRun=[a.postRun]);a.postRun.length;)ea.unshift(a.postRun.shift());
N(ea)}}if(!(0<z)){if(a.preRun)for("function"==typeof a.preRun&&(a.preRun=[a.preRun]);a.preRun.length;)fa.unshift(a.preRun.shift());N(fa);0<z||(a.setStatus?(a.setStatus("Running..."),setTimeout(function(){setTimeout(function(){a.setStatus("")},1);c()},1)):c())}}function Q(c){this.L=c;this.frames=this.onload=this.imageData=null;this.loop_count=0}var a={},F={},x;for(x in a)a.hasOwnProperty(x)&&(F[x]=a[x]);var ca="object"===typeof window,E="function"===typeof importScripts,v="",A,B;if("object"===typeof process&&
"object"===typeof process.versions&&"string"===typeof process.versions.node){v=E?require("path").dirname(v)+"/":__dirname+"/";var ha=function(c,b){A||(A=require("fs"));B||(B=require("path"));c=B.normalize(c);return A.readFileSync(c,b?null:"utf8")};var L=function(c){c=ha(c,!0);c.buffer||(c=new Uint8Array(c));c.buffer||w("Assertion failed: undefined");return c};var M=function(c,b,d){A||(A=require("fs"));B||(B=require("path"));c=B.normalize(c);A.readFile(c,function(e,f){e?d(e):b(f.buffer)})};1<process.argv.length&&
process.argv[1].replace(/\\/g,"/");process.argv.slice(2);"undefined"!==typeof module&&(module.exports=a);process.on("uncaughtException",function(c){throw c;});process.on("unhandledRejection",w);a.inspect=function(){return"[Emscripten Module object]"}}else if(ca||E)E?v=self.location.href:"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src),v=0!==v.indexOf("blob:")?v.substr(0,v.lastIndexOf("/")+1):"",ha=function(c){var b=new XMLHttpRequest;b.open("GET",c,!1);b.send(null);
return b.responseText},E&&(L=function(c){var b=new XMLHttpRequest;b.open("GET",c,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),M=function(c,b,d){var e=new XMLHttpRequest;e.open("GET",c,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):d()};e.onerror=d;e.send(null)};a.print||console.log.bind(console);var C=a.printErr||console.warn.bind(console);for(x in F)F.hasOwnProperty(x)&&(a[x]=F[x]);F=null;var D;a.wasmBinary&&
(D=a.wasmBinary);"object"!==typeof WebAssembly&&w("no native wasm support detected");var ia,Z=!1,Y="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0,V,H,O,fa=[],da=[],ea=[],z=0,R=null,G=null;a.preloadedImages={};a.preloadedAudios={};var u="bpgdec.wasm";aa(u)||(u=ja(u));var la={a:function(){w()},b:function(c,b,d){H.copyWithin(c,b,b+d)},c:function(){w("OOM")}};(function(){function c(f){a.asm=f.exports;ia=a.asm.d;f=ia.buffer;a.HEAP8=V=new Int8Array(f);a.HEAP16=new Int16Array(f);a.HEAP32=
new Int32Array(f);a.HEAPU8=H=new Uint8Array(f);a.HEAPU16=new Uint16Array(f);a.HEAPU32=new Uint32Array(f);a.HEAPF32=new Float32Array(f);a.HEAPF64=new Float64Array(f);O=a.asm.f;da.unshift(a.asm.e);z--;a.monitorRunDependencies&&a.monitorRunDependencies(z);0==z&&(null!==R&&(clearInterval(R),R=null),G&&(f=G,G=null,f()))}function b(f){c(f.instance)}function d(f){return ka().then(function(p){return WebAssembly.instantiate(p,e)}).then(f,function(p){C("failed to asynchronously prepare wasm: "+p);w(p)})}var e=
{a:la};z++;a.monitorRunDependencies&&a.monitorRunDependencies(z);if(a.instantiateWasm)try{return a.instantiateWasm(e,c)}catch(f){return C("Module.instantiateWasm callback failed with error: "+f),!1}(function(){return D||"function"!==typeof WebAssembly.instantiateStreaming||aa(u)||u.startsWith("file://")||"function"!==typeof fetch?d(b):fetch(u,{credentials:"same-origin"}).then(function(f){return WebAssembly.instantiateStreaming(f,e).then(b,function(p){C("wasm streaming compile failed: "+p);C("falling back to ArrayBuffer instantiation");
return d(b)})})})();return{}})();a.___wasm_call_ctors=function(){return(a.___wasm_call_ctors=a.asm.e).apply(null,arguments)};a._malloc=function(){return(a._malloc=a.asm.g).apply(null,arguments)};a._free=function(){return(a._free=a.asm.h).apply(null,arguments)};a._bpg_decoder_get_info=function(){return(a._bpg_decoder_get_info=a.asm.i).apply(null,arguments)};a._bpg_decoder_start=function(){return(a._bpg_decoder_start=a.asm.j).apply(null,arguments)};a._bpg_decoder_get_frame_duration=function(){return(a._bpg_decoder_get_frame_duration=
a.asm.k).apply(null,arguments)};a._bpg_decoder_get_line=function(){return(a._bpg_decoder_get_line=a.asm.l).apply(null,arguments)};a._bpg_decoder_open=function(){return(a._bpg_decoder_open=a.asm.m).apply(null,arguments)};a._bpg_decoder_decode=function(){return(a._bpg_decoder_decode=a.asm.n).apply(null,arguments)};a._bpg_decoder_close=function(){return(a._bpg_decoder_close=a.asm.o).apply(null,arguments)};var W=a.stackSave=function(){return(W=a.stackSave=a.asm.p).apply(null,arguments)},X=a.stackRestore=
function(){return(X=a.stackRestore=a.asm.q).apply(null,arguments)},J=a.stackAlloc=function(){return(J=a.stackAlloc=a.asm.r).apply(null,arguments)};a.ccall=U;a.cwrap=function(c,b,d,e){d=d||[];var f=d.every(function(p){return"number"===p});return"string"!==b&&f&&!e?T(c):function(){return U(c,b,d,arguments,e)}};var I;G=function b(){I||P();I||(G=b)};a.run=P;if(a.preInit)for("function"==typeof a.preInit&&(a.preInit=[a.preInit]);0<a.preInit.length;)a.preInit.pop()();P();window.BPGDecoder=Q;Q.prototype=
{B:a.cwrap("malloc","number",["number"]),v:a.cwrap("free","void",["number"]),J:a.cwrap("bpg_decoder_open","number",[]),F:a.cwrap("bpg_decoder_decode","number",["number","array","number"]),H:a.cwrap("bpg_decoder_get_info","number",["number","number"]),K:a.cwrap("bpg_decoder_start","number",["number","number"]),G:a.cwrap("bpg_decoder_get_frame_duration","void",["number","number","number"]),I:a.cwrap("bpg_decoder_get_line","number",["number","number"]),D:a.cwrap("bpg_decoder_close","void",["number"]),
load:function(b){var d=new XMLHttpRequest,e=this;d.open("get",b,!0);d.responseType="arraybuffer";d.onload=function(f){e.C(d,f)};d.send()},C:function(b){var d=new Uint8Array(b.response),e,f,p,m;b=this.J();if(0>this.F(b,d,d.length))console.log("could not decode image");else{var q=this.B(20);this.H(b,q);var y=a.HEAPU8;var h=a.HEAPU16;var l=a.HEAPU32;d=l[q>>2];var k=l[q+4>>2];var n=h[q+16>>1];var g=4*d;var r=this.B(g);var t=0;for(m=[];!(0>this.K(b,1));){this.G(b,q,q+4);var K=1E3*l[q>>2]/l[q+4>>2];h=this.L.createImageData(d,
k);var ma=h.data;for(p=e=0;p<k;p++)for(this.I(b,r),f=0;f<g;f=f+1|0)ma[e]=y[r+f|0]|0,e=e+1|0;m[t++]={img:h,duration:K}}this.v(r);this.v(q);this.D(b);this.loop_count=n;this.frames=m;this.imageData=m[0].img;if(this.onload)this.onload()}}};window.onload=function(){var b,d;var e=document.images;var f=e.length;var p=[];for(b=0;b<f;b++){var m=e[b];var q=m.src;".bpg"==q.substr(-4,4).toLowerCase()&&(p[p.length]=m)}f=p.length;for(b=0;b<f;b++){m=p[b];q=m.src;e=document.createElement("canvas");m.id&&(e.id=m.id);
m.className&&(e.className=m.className);if(d=m.getAttribute("width")|0)e.style.width=d+"px";if(d=m.getAttribute("height")|0)e.style.height=d+"px";m.parentNode.replaceChild(e,m);d=e.getContext("2d");m=new Q(d);m.onload=function(y,h){function l(){var r=k.u;++r>=n.length&&(0==k.loop_count||k.A<k.loop_count?(r=0,k.A++):r=-1);0<=r&&(k.u=r,h.putImageData(n[r].img,0,0),setTimeout(l,n[r].duration))}var k=this,n=this.frames,g=n[0].img;y.width=g.width;y.height=g.height;h.putImageData(g,0,0);1<n.length&&(k.u=
0,k.A=0,setTimeout(l,n[0].duration))}.bind(m,e,d);m.load(q)}}})();
